### ISSUE TITLE
Core Service Logic

### ISSUE THREAD

**Issue by Kaizoku01** [Kaizoku01/gpt-module-package#2]
## Tasks
- [x] Create Class `OpenAiService` which will hold the methods for requesting and recieving from the openAi API
- [x] Make use of `RequestModel` Class for requesting.
- [x] Make functionality for `GPT-3.5-turbo` & `GPT-4`

### Notes
- for 3.5
  - string input <--> string output.
- for 4
  - string/Image input <--> string output.
